/* 
 This project aims to perform an in-depth analysis of a Walmart sales dataset to uncover critical
 business insights and inform strategic decision-making. By leveraging SQL for data cleaning, 
 transformation, and querying, this analysis will provide actionable findings related to sales trends,
 product performance, and customer behaviour.
*/

CREATE DATABASE project;

SHOW TABLES;

SELECT * FROM walmart_customer_purchases;

SELECT COUNT(*) FROM walmart_customer_purchases;

		# CHECKING FOR NULL VALUES

SELECT * FROM walmart_customer_purchases
WHERE
  Customer_ID IS NULL
  OR Age IS NULL
  OR Gender IS NULL
  OR City IS NULL
  OR Category IS NULL
  OR Product_Name IS NULL
  OR Purchase_Date IS NULL
  OR Purchase_Amount IS NULL
  OR Payment_Method IS NULL
  OR Discount_Applied IS NULL
  OR Rating IS NULL
  OR Repeat_Customer IS NULL;

SELECT * FROM walmart_customer_purchases;

	    # IDENTIFYING UNIQUE LIST OF PRODUCTS

SELECT
  DISTINCT product_name AS Product_List
FROM walmart_customer_purchases;

		# PRODUCTS BASED ON CATEGORY

SELECT 
  DISTINCT product_name, category
FROM walmart_customer_purchases
ORDER BY category;

		# RANGE OF SALES

SELECT
  MIN(purchase_date) AS First_Sale_Date,
  MAX(purchase_date) AS Last_Sale_Date
FROM walmart_customer_purchases;

		# TOTAL REVENUE GENERATED BY WALMART IN THE LAST YEAR

SELECT 
  ROUND(SUM(purchase_amount), 2) AS Total_revenue_last_year
FROM walmart_customer_purchases;
  
		# TOP TWO CATEGORIES THAT CONTRIBUTED MOST TO THE REVENUE

SELECT 
  category,
  ROUND(SUM(purchase_amount), 2) AS Most_contributions
FROM walmart_customer_purchases
GROUP BY category
ORDER BY Most_contributions DESC
Limit 2;
  
		# TOP FIVE BEST-SELLING PRODUCTS BY SALES AMOUNT

SELECT 
  product_name,
  ROUND(SUM(purchase_amount), 2) AS Best_selling_products
FROM walmart_customer_purchases
GROUP BY product_name
ORDER BY Best_selling_products DESC
LIMIT 5;
  
		# GENDER-WISE SPENDING DISTRIBUTION

SELECT
  gender,
  ROUND(SUM(purchase_amount), 2) AS Total_spends_gender_wise
FROM walmart_customer_purchases
GROUP BY gender
ORDER BY Total_spends_gender_wise DESC;
  
		# REVENUE GENERATED BY EACH REPEAT CUSTOMERS
  
SELECT
  customer_id,
  repeat_customer,
  ROUND(SUM(purchase_amount), 2) AS Total_revenue
FROM walmart_customer_purchases
WHERE repeat_customer = 'yes'
GROUP BY customer_id;
  
		# AVERAGE CUSTOMER RATING FOR EACH PRODUCT/CATEGORY

SELECT
  product_name,
  category,
  AVG(rating) AS Average_rating
FROM walmart_customer_purchases
GROUP BY product_name, category
ORDER BY Average_rating DESC;

		# COMMON PAYMENT METHODS BASED ON CATEGORY  

SELECT
    category,
    payment_method,
    COUNT(*) AS Number_of_payments
FROM walmart_customer_purchases
GROUP BY payment_method, category
ORDER BY COUNT(*) DESC; 

		# MINUMUM/MAXIMUM/AVERAGE RATING FOR EACH CITY

SELECT
  city,
  category,
  MIN(rating) as minimum_rating,
  MAX(rating) as maximum_rating,
  ROUND(AVG(rating), 2) as average_rating
FROM walmart_customer_purchases
GROUP BY category, city;

		# TOP-PERFORMING MONTHS FOR WALMART

SELECT 
  YEAR(purchase_date) AS Year,
  MONTH(purchase_date) AS Month,
  COUNT(DISTINCT customer_id) AS Unique_customers,
  ROUND(SUM(purchase_amount), 2) AS Total_purchase_amount, 
  ROUND(AVG(purchase_amount), 2) AS Average_transaction_value
FROM walmart_customer_purchases
GROUP BY YEAR(purchase_date), MONTH(purchase_date)
ORDER BY Total_purchase_amount DESC;

		# TO FIND THE TOP-SELLING PRODUCT IN EACH CATEGORY

WITH category_sales AS (
  SELECT
    category,
    product_name,
    ROUND(SUM(purchase_amount), 2) AS Total_revenue,
    RANK() OVER (PARTITION BY category ORDER BY SUM(purchase_amount) DESC) AS Rank_no
  FROM walmart_customer_purchases
  GROUP BY category, product_name
)
SELECT 
  category,
  product_name,
  Total_revenue
FROM category_sales
WHERE Rank_no = 1
ORDER BY category;

/*
Through the analysis of Walmart's sales data, key insights were gained regarding financial performance,
 product success, and customer behavior. The analysis determined the total revenue from 2024 to 2025,
 identified the top contributing categories, and highlighted the five best-selling products,
 revealing the most profitable aspects of the business. By examining repeat customers,
 the analysis quantified their significant contribution to overall revenue, underscoring their
 importance for sustained growth. Additionally, product and category ratings, combined with 
 city-specific performance metrics, provided a localized view of customer satisfaction,
 while the identification of top-performing months helps inform future seasonal strategies.
 */











